sudo: required

language: node_js

services:
  - docker

before_install:
  - docker build -t momensherif/react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true momensherif/react-app npm run test