version: '3'

services:
  postgres:
    container_name: Postgress
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres_password

  redis:
    container_name: Redis
    image: redis

  api:
    container_name: Server
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/app/node_modules
      - ./server:/usr/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432

  worker:
    container_name: worker
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/app/node_modules
      - ./woker:/usr/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  client:
    stdin_open: true
    container_name: Client
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/app/node_modules
      - ./client:/usr/app

  nginx:
    container_name: Nginx
    restart: always
    depends_on:
      - api
      - client
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - 3000:80
